version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3030:3030
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: grocery_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: grocery_db
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --bind-address=0.0.0.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
